
[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/kitech/qt.go"

[[constraint]]
  name = "mvdan.cc/xurls"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
